// Mock data for the table
export const artists = [
  {
    id: 1,
    name: "Taylor Swift",
    song: "Cruel Summer",
    album: "1989 (Taylor's Version)",
    releaseDate: "2023-10-27",
    genre: "Pop",
  },
  {
    id: 2,
    name: "The Weeknd",
    song: "Blinding Lights",
    album: "After Hours",
    releaseDate: "2020-03-20",
    genre: "Pop/R&B",
  },
  {
    id: 3,
    name: "Ed Sheeran",
    song: "Shape of You",
    album: "÷ (Divide)",
    releaseDate: "2017-03-03",
    genre: "Pop",
  },
  {
    id: 4,
    name: "Ariana Grande",
    song: "Thank U, Next",
    album: "Thank U, Next",
    releaseDate: "2019-02-08",
    genre: "Pop",
  },
  {
    id: 5,
    name: "Billie Eilish",
    song: "Bad Guy",
    album: "When We All Fall Asleep, Where Do We Go?",
    releaseDate: "2019-03-29",
    genre: "Pop",
  },
  {
    id: 6,
    name: "Bruno Mars",
    song: "Uptown Funk",
    album: "Uptown Special",
    releaseDate: "2014-11-10",
    genre: "Funk/Pop",
  },
  {
    id: 7,
    name: "Dua Lipa",
    song: "Levitating",
    album: "Future Nostalgia",
    releaseDate: "2020-03-27",
    genre: "Pop",
  },
  {
    id: 8,
    name: "Drake",
    song: "God's Plan",
    album: "Scary Hours 2",
    releaseDate: "2018-02-16",
    genre: "Hip Hop",
  },
  {
    id: 9,
    name: "Katy Perry",
    song: "Roar",
    album: "Prism",
    releaseDate: "2013-08-10",
    genre: "Pop",
  },
  {
    id: 10,
    name: "Harry Styles",
    song: "Watermelon Sugar",
    album: "Fine Line",
    releaseDate: "2019-11-16",
    genre: "Pop/Rock",
  },
  {
    id: 11,
    name: "Lil Nas X",
    song: "Montero (Call Me By Your Name)",
    album: "Montero",
    releaseDate: "2021-03-26",
    genre: "Hip Hop/Pop",
  },
  {
    id: 12,
    name: "Post Malone",
    song: "Circles",
    album: "Hollywood's Bleeding",
    releaseDate: "2019-08-30",
    genre: "Pop/Rock",
  },
  {
    id: 13,
    name: "Shawn Mendes",
    song: "Stitches",
    album: "Handwritten",
    releaseDate: "2015-04-28",
    genre: "Pop",
  },
  {
    id: 14,
    name: "Rihanna",
    song: "Diamonds",
    album: "Unapologetic",
    releaseDate: "2012-10-11",
    genre: "Pop/R&B",
  },
  {
    id: 15,
    name: "Sia",
    song: "Chandelier",
    album: "1000 Forms of Fear",
    releaseDate: "2014-03-17",
    genre: "Pop",
  },
  {
    id: 16,
    name: "Charlie Puth",
    song: "Attention",
    album: "Voicenotes",
    releaseDate: "2017-04-21",
    genre: "Pop",
  },
  {
    id: 17,
    name: "Selena Gomez",
    song: "Lose You to Love Me",
    album: "Rare",
    releaseDate: "2019-10-23",
    genre: "Pop",
  },
  {
    id: 18,
    name: "Miley Cyrus",
    song: "Wrecking Ball",
    album: "Bangerz",
    releaseDate: "2013-09-09",
    genre: "Pop",
  },
  {
    id: 19,
    name: "Lizzo",
    song: "Truth Hurts",
    album: "Cuz I Love You",
    releaseDate: "2017-09-19",
    genre: "Pop/Rap",
  },
  {
    id: 20,
    name: "Kendrick Lamar",
    song: "HUMBLE.",
    album: "DAMN.",
    releaseDate: "2017-03-30",
    genre: "Hip Hop",
  },
  {
    id: 21,
    name: "Travis Scott",
    song: "SICKO MODE",
    album: "Astroworld",
    releaseDate: "2018-08-03",
    genre: "Hip Hop",
  },
];
